cartolafc_endpoint = {"mercado_status": "https://api.cartolafc.globo.com/mercado/status",
"mercado_destaque": "https://api.cartolafc.globo.com/mercado/destaques",
"patrocinadores": "https://api.cartolafc.globo.com/patrocinadores",
"rodadas": "https://api.cartolafc.globo.com/rodadas",
"partidas": "https://api.cartolafc.globo.com/partidas",
"partida_rodada": "https://api.cartolafc.globo.com/partidas/{rodada}",
"clubes": "https://api.cartolafc.globo.com/clubes",
"atletas": "https://api.cartolafc.globo.com/atletas/mercado",
"atletas_pontuados" : "https://api.cartolafc.globo.com/atletas/pontuados",
"clubes_destaque": "https://api.cartolafc.globo.com/pos-rodada/destaques",
"busca_clube": "https://api.cartolafc.globo.com/times?q={nome_time}",
"busca_clube_slug": "https://api.cartolafc.globo.com/time/slug/{slug_time}",
"busca_clube_slug_rodada": "https://api.cartolafc.globo.com/time/slug/{slug_time}/{rodada}",
"busca_liga": "https://api.cartolafc.globo.com/ligas?q={nome_liga}",
"busca_liga_slug": "https://api.cartolafc.globo.com/auth/liga/{slug_liga}",
"info_clube_user": "https://api.cartolafc.globo.com/auth/time",
"info_clube_user_detalhes": "https://api.cartolafc.globo.com/auth/time/info",
"user_ligas": "https://api.cartolafc.globo.com/auth/ligas",
"esquemas_taticos": "https://api.cartolafc.globo.com/esquemas",
"autenticacao": 'https://login.globo.com/api/authentication'
}