# -*- coding: utf-8 -*-
cartolafc_endpoint = {"mercado_status": ["https://api.cartolafc.globo.com/mercado/status","dict"],
"mercado_destaque": ["https://api.cartolafc.globo.com/mercado/destaques","list"],
"patrocinadores": ["https://api.cartolafc.globo.com/patrocinadores","index"],
"rodadas": ["https://api.cartolafc.globo.com/rodadas","list"],
"partidas": ["https://api.cartolafc.globo.com/partidas","dict"],
"partida_rodada": ["https://api.cartolafc.globo.com/partidas/?q=rodada={rodada}", "index"],
"clubes": ["https://api.cartolafc.globo.com/clubes","index"],
"atletas": ["https://api.cartolafc.globo.com/atletas/mercado","dict"],
"atletas_pontuados" : ["https://api.cartolafc.globo.com/atletas/pontuados", "index"],
# "clubes_destaque": ["https://api.cartolafc.globo.com/pos-rodada/destaques","dict"],
"busca_clube": ["https://api.cartolafc.globo.com/times?q={nome_time}","list"],
"busca_clube_slug": ["https://api.cartolafc.globo.com/time/slug/{slug_time}", "dict"],
"busca_clube_slug_rodada": ["https://api.cartolafc.globo.com/time/slug/{slug_time}/{rodada}","dict"],
"busca_liga": ["https://api.cartolafc.globo.com/ligas?q={nome_liga}","list"],
"busca_liga_slug": ["https://api.cartolafc.globo.com/auth/liga/{slug_liga}","dict"],
"info_clube_user": ["https://api.cartolafc.globo.com/auth/time","dict"],
"info_clube_user_detalhes": ["https://api.cartolafc.globo.com/auth/time/info","dict"],
"user_ligas": ["https://api.cartolafc.globo.com/auth/ligas","dict"],
"esquemas_taticos": ["https://api.cartolafc.globo.com/esquemas","dict"],
"autenticacao": ["https://login.globo.com/api/authentication","dict"]
}